image: python:latest

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test-job:
  stage: test
  script:
    - cd sprint4 && python3 test_compiler.py
