image: python:latest

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test-s1:
  stage: test
  script:
    - cd sprint1 && make test

test-s2:
  stage: test
  script:
    - cd sprint2 && make test

test-s3:
  stage: test
  script:
    - cd sprint3 && make test

test-s4:
  stage: test
  script:
    - cd sprint4 && make test
